### ISSUE TITLE
Add  License to Ease Collaboration and Foster Usage

### ISSUE THREAD

**Issue by sthagen** [gabor-meszaros/reporchestrator#3]
I suggest to add a LICENSE file that suits the author's ideas such that GitHub automatic tooling can categorize the repository. In this way the terms will be obvious for potential collaborators and users.

**Comment by gabor-meszaros** [comment]
Very good idea @sdrees ! Would you recommend a license that is known widely and more or less says "use/modify it freely but mention that you used it"?

**Comment by sthagen** [comment]
I am opinionated on this, but maybe MIT is nice and kindly requesting mention of use to me always  wins against legal language enforcing that. You could try this way of adding MIT or some other license: https://github.com/gabor-meszaros/reporchestrator/community/license/new?template=MIT

**Comment by gabor-meszaros** [comment]
If everything were that easy... Thank you for opening the issue and recommending a solution!
